const mongoose = require('mongoose')

var acordaoSchema = new mongoose.Schema({
    _id: Number,
    producerId: String,
    Processo: String,
    url: String,
    tribunal: String,
    'Data do Acordão': String,
    Descritores: [String],
    Relator: String,
    Votação: String,
    'Texto Integral': String,
    Decisão: String,
    'Meio Processual': String,
    'Nº do Documento': String,
    'Nº Convencional': String,
    'Sumário': String,
    Privacidade: String,
    'Legislação Nacional': String,
    'Decisão Texto Integral': String,
    'Áreas Temáticas': [String],
    'Tribunal': String,
    Recorrente: String,
    'Recorridos': [String],
    'Data de Entrada': String,
    'Jurisprudência Nacional': String,
    Objecto: String,
    Reclamações: String,
    'Ano da Publicação': String,
    'Indicações Eventuais': String,
    'Tribunal Recurso': String,
    Data: String,
    'Juízo ou Secção': String,
    'Tribunal Recorrido': String,
    'Processo no Tribunal Recurso': String,
    '1ª Pág. de Publicação do Acordão': String,
    Apêndice: String,
    'Data do Apêndice': String,
    'Processo no Tribunal Recorrido': String,
    'Referência a Doutrina': String,
    'Data Dec. Recorrida': String,
    Página: String,
    'Referências de Publicação': [String],
    'Texto Parcial': String,
    'Parecer Ministério Público': String,
    'Referência a Doutrina': String,
    Espécie: String,
    Acordão: String,
    Requerente: String,
    Requerido: String,
    'Nº do Volume': String,
    Magistrado: String,
    Contencioso: String,
    'Nº Processo/TAF': String,
    'Sub-Secção': String,
    'Normas Apreciadas': String,
    Constituição: String,
    'Nº do Diário da República': String,
    'Série do Diário da República': String,
    'Data do Diário da República': String,
    'Página do Diário da República': String,
    'Referência a Pareceres': String,
    'Disponível na JTCA': String,
    'Legislação Comunitária': String,
    'Referências Internacionais': String,
    'Normas Declaradas Inconst.': String,
    'Normas Suscitadas': String,
    'Voto Vencido': String,
    'Apenso': String,
    'Jurisprudência Internacional': String,
    'Legislação Estrangeira': String,
    'Recusa Aplicação': String,
    'Declaração de Voto': String,
    'Tribunal 1ª Instância': String,
    'Data da Decisão': String,
    'Texto das Cláusulas Abusivas': String,
    'Recurso': String,
    'Autor': String,
    'Réu': String,
    'Tipo de Contrato': String,
    'Tipo de Ação': String,
    'Volume dos Acordãos do T.C.': String,
    'Página do Volume': String,
    'Página do Boletim do M.J.': String,
    'Nº do Boletim do M.J.': String,
    'Jurisprudência Constitucional': String,
    'Nº Único do Processo': String,
    'Observações': String,
    'Data da Decisão Sumária': String,
    'Jurisprudência Estrangeira': String,
    'Outras Publicações': String,
    'Referência Processo': String,
    'Outra Jurisprudência': String,
    'Data da Reclamação': String,
    'Peça Processual': String,
    'Tema': String,
    'Data da Decisão Singular': String,
});

module.exports = mongoose.model('acordao', acordaoSchema);